### ISSUE TITLE
Environmental issues regarding the implementation of AES encryption process

### ISSUE THREAD

**Issue by 15646739752** [hacl-star/hacl-star#544]
Hello, I am using a series of files such as EverCrypt_AEAD to realize AES encryption and decryption process. I would like to ask about its working configuration. Does its implementation need ocaml? And your configure file, is it a choice between it and config.h

**Comment by msprotz** [comment]
You do not need OCaml; a simple "./configure && make" in dist/gcc-compatible should work.

If ./configure does not give the results you want (e.g. because you're cross-compiling to a specific architecture), please edit Makefile.config and/or config.h by hand -- I can provide help if you have specific questions. Thanks!
