### ISSUE TITLE
Unbound module when compiling new HACL* spec (OCaml compilation)

### ISSUE THREAD

**Issue by felipelisboa-ml** [hacl-star/hacl-star#837]
I am writing a new HACL* spec, which I am looking to run some sanity tests on.

I extracted the code to OCaml, and tried to compile it using:
```
OCAML_PATH="$FSTAR_HOME/bin" ocamlbuild -use-ocamlfind -pkg batteries -pkg fstar.lib Spec_LRBC2.cmxa
```

But the ocaml compiler says:
```
Unbound module Lib_IntTypes
```

Following that, I tried to compile it again using
```
OCAML_PATH="$FSTAR_HOME/bin" ocamlbuild -use-ocamlfind -pkg batteries -pkg fstar.lib -lib $HACL_HOME/obj/Lib_IntTypes.cmx Spec_LRBC2.cmxa
```

But same error happens. So my question is: how to link the generated OCaml file to HACL* lib? Should I install it manually using ocamlfind?

**Comment by msprotz** [comment]
Can you try linking against `obj/libhaclml.cmxa`? It contains all of the spec modules, extracted to OCaml, linked together, for the benefits of clients who want to link against them.

ocamlbuild is super deprecated these days, so you'll have to figure out how to instruct ocamlbuild to link against libhaclml.cmxa -- conceivably, you could write a META file for it, put it in obj/, pass that path to OCAMLPATH (*not* OCAML_PATH), then pass `-lib haclml` to ocamlbuild, but I'm not sure, it's been a long while since I used ocamlbuild

@victor-dumitrescu may know better about how to achieve this using dune

**Comment by msprotz** [comment]
No response, closing.
